use_frameworks!

target 'CloudVisionSwift_Example' do
  pod 'CloudVisionSwift', :path => '../'

  target 'CloudVisionSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
